export const userRows = [
    { id: 1, name: 'amika', email: 'SJSU', age:10,location:'pune',comments:'ok' },
    { id: 2, name: 'amika', email: 'SJSU', age:20,location:'pune',comments:'ok' },
    { id: 3, name: 'amika', email: 'SJSU', age:40,location:'pune',comments:'ok' },
    { id: 4, name: 'amika', email: 'SJSU', age:70,location:'pune',comments:'ok' },
    { id: 5, name: 'amika', email: 'SJSU', age:80,location:'pune',comments:'ok' },
    { id: 6, name: 'amika', email: 'SJSU', age:100,location:'pune',comments:'ok' },
    { id: 189, name: 'amika', email: 'SJSU', age:1,location:'pune',comments:'ok' },
    { id: 14, name: 'amika', email: 'SJSU', age:30,location:'pune',comments:'ok' },
    { id: 15, name: 'amika', email: 'SJSU', age:21,location:'pune',comments:'ok' },
    { id: 17, name: 'amika', email: 'SJSU', age:22,location:'pune',comments:'ok' },
    { id: 19, name: 'amika', email: 'SJSU', age:89,location:'pune',comments:'ok' },
    { id: 21, name: 'amika', email: 'SJSU', age:87,location:'pune',comments:'ok' },
    { id: 23, name: 'amika', email: 'SJSU', age:12,location:'pune',comments:'ok' },
    { id: 31, name: 'amika', email: 'SJSU', age:41,location:'pune',comments:'ok' },
    { id: 41, name: 'amika', email: 'SJSU', age:98,location:'pune',comments:'ok' },
    { id: 10, name: 'amika', email: 'SJSU', age:76,location:'pune',comments:'ok' },
    { id: 91, name: 'amika', email: 'SJSU', age:87,location:'pune',comments:'ok' },
  ]
 
